import type { Metadata } from "next";
import { poppins } from "@/lib/utils";
import "@/styles/globals.css";
import Navbar from "@/components/navbar/Navbar";
import Provider from "../../context/Providers";

export const metadata: Metadata = {
    title: "Quiz101",
    description: "Generated by create next app",
};

export default function StudentRootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${poppins.className} `}>
                <Provider>
                    <Navbar />
                    <div className="w-full max-w-7xl flex flex-col mx-auto">
                        {children}
                    </div>
                </Provider>
            </body>
        </html>
    );
}
