import type { Metadata } from "next";
import { poppins } from "@/lib/utils";
import "@/styles/globals.css";
import GlobalProviders from "../../context/GlobalProviders";
import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
    title: "TestTwist",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <GlobalProviders>
                    <Navbar />
                    {children}
                </GlobalProviders>
            </body>
        </html>
    );
}
