import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Onboardingform from "@/components/auth/onboarding/Onboardingform";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import React from "react";

export const metadata: Metadata = {
    title: "Manage your Account | QuizTwist",
    description: "Generated by create next app",
};

const OnBoardingPage = async () => {
    const session = await getServerSession(authOptions);

    if (session?.user.role !== "Guest") redirect("/dashboard");

    return (
        <div className="w-full h-[90vh] flex justify-center items-center">
            <Onboardingform />
        </div>
    );
};

export default OnBoardingPage;
