import OnBoardingForm from "@/components/forms/OnBoardingForm";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Manage your Account | Quiz101",
    description: "Generated by create next app",
};

const OnBoardingPage = async () => {
    return (
        <div>
            <OnBoardingForm />
        </div>
    );
};

export default OnBoardingPage;
