import type { Metadata } from "next";
import QuizTemplates from "@/components/room/QuizTemplates";
import UpcomingQuiz from "@/components/room/UpcomingQuiz";
import Classcode from "@/components/room/Classcode";

export const metadata: Metadata = {
    title: "Classwork | TestTwist",
    description: "Generated by create next app",
};

const ClassworkPage = () => {
    return (
        <div className="w-full max-w-6xl mx-auto flex gap-10 p-6">
            <div className="flex flex-col items-center gap-4">
                <UpcomingQuiz />
                <Classcode />
            </div>

            <div className="w-full flex flex-col">
                <p className="mb-2">Start a new Test</p>
                <QuizTemplates />
                <div className="w-full flex flex-col bg-slate-500 mt-10">
                    <p>Quize</p>
                </div>
            </div>
        </div>
    );
};

export default ClassworkPage;
