import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "People | Quiz101",
    description: "Generated by create next app",
};

const PeoplePage = () => {
    return (
        <div className="w-full flex flex-col p-20">
            <div className="w-full p-4"></div>
            <div className="w-full flex flex-col gap-4">
                <h1 className="text-xl font-medium">Teacher</h1>
                <div className="w-full flex flex-wrap items-center gap-6">
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                </div>
            </div>
            <hr className="my-6" />
            <div className="w-full flex flex-col gap-4 ">
                <h1 className="text-xl font-medium">Students</h1>
                <div className="w-full flex flex-wrap items-center gap-4">
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                    <div className="flex flex-col items-center gap-1">
                        <Avatar className="w-14 h-14">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <p className="text-sm">Mhica Shane</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default PeoplePage;
