import type { Metadata } from "next";
import { poppins } from "@/lib/utils";
import "@/styles/globals.css";
import Navbar from "@/components/navbar/Navbar";
import GlobalProviders from "../../context/GlobalProviders";
import Sidebar from "@/components/sidebar/Sidebar";

export const metadata: Metadata = {
    title: "Dashboard | TestTwist",
    description: "Generated by create next app",
};

export default async function TeacherRootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${poppins.className} bg-background`}>
                <GlobalProviders>
                    <Navbar />
                    <div className="w-full relative flex">
                        <Sidebar />
                        <div className="w-full flex flex-col items-center mx-auto">
                            {children}
                        </div>
                    </div>
                </GlobalProviders>
            </body>
        </html>
    );
}
